In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
import seaborn

In [20]:
a=pd.read_csv('bill_authentication.csv')
a

Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [21]:
a.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [22]:
a.tail()

Variance  Skewness  Curtosis  Entropy  Class
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

In [23]:
a.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [24]:
a['Class'].unique()

array([0, 1], dtype=int64)

In [25]:
a['Entropy'].unique()

array([-0.44699, -1.4621 ,  0.10645, ..., -1.2953 , -0.55949, -2.7771 ])

In [26]:
a.shape

(1372, 5)

In [27]:
a.ndim

2

In [30]:
X=a.iloc[:,:-1]
y=a.iloc[:,-1]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
# train_test_data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.22, random_state=42)

In [33]:
X_train

Variance  Skewness  Curtosis  Entropy
209     2.1721  -0.73874   5.46720 -0.72371
693     1.5478   9.18140  -1.63260 -1.73750
140     2.0911   0.94358   4.55120  1.23400
963    -3.3863 -12.98890  13.05450 -2.72020
944    -2.1210  -0.05588   1.94900  1.35300
...        ...       ...       ...      ...
1095    1.1640   3.91300  -4.55440 -3.86720
1130   -2.2918  -7.25700   7.95970  0.92110
1294   -7.0364   9.29310   0.16594 -4.53960
860    -3.4605   2.69010   0.16165 -1.02240
1126   -3.3582  -7.24040  11.44190 -0.57113

[1070 rows x 4 columns]

In [34]:
y_train

209     0
693     0
140     0
963     1
944     1
       ..
1095    1
1130    1
1294    1
860     1
1126    1
Name: Class, Length: 1070, dtype: int64

In [35]:
# training_Data in KNN

In [36]:
 from sklearn.neighbors import KNeighborsClassifier

In [37]:
reg = KNeighborsClassifier(n_neighbors=3)

In [38]:
reg.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [39]:
y_train_pred = reg.predict(X_train)

In [40]:
training_data = pd.DataFrame(X_train)
training_data['y_train'] = y_train
training_data['Y_train_pred'] = y_train_pred


training_data

Variance  Skewness  Curtosis  Entropy  y_train  Y_train_pred
209     2.1721  -0.73874   5.46720 -0.72371        0             0
693     1.5478   9.18140  -1.63260 -1.73750        0             0
140     2.0911   0.94358   4.55120  1.23400        0             0
963    -3.3863 -12.98890  13.05450 -2.72020        1             1
944    -2.1210  -0.05588   1.94900  1.35300        1             1
...        ...       ...       ...      ...      ...           ...
1095    1.1640   3.91300  -4.55440 -3.86720        1             1
1130   -2.2918  -7.25700   7.95970  0.92110        1             1
1294   -7.0364   9.29310   0.16594 -4.53960        1             1
860    -3.4605   2.69010   0.16165 -1.02240        1             1
1126   -3.3582  -7.24040  11.44190 -0.57113        1             1

[1070 rows x 6 columns]

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [42]:
confusion_matrix(y_train,y_train_pred)

array([[595,   1],
       [  0, 474]], dtype=int64)

In [43]:
accuracy_score(y_train,y_train_pred)

0.9990654205607477